# values.yaml - Bitwarden Secrets Manager Operator configuration

# Operator configuration
operator:
  image:
    repository: bitwarden/sm-operator
    tag: "0.3.0"
    pullPolicy: IfNotPresent
  
  # Resource limits
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Number of operator replicas
  replicaCount: 1
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# RBAC configuration
rbac:
  create: true

# Webhook configuration (if needed)
webhook:
  enabled: true
  port: 9443
  
# Metrics configuration
metrics:
  enabled: true
  port: 8080
  
# Health check configuration
health:
  enabled: true
  port: 8081

# Node selector and tolerations (optional)
nodeSelector: {}
tolerations: []
affinity: {}

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  fsGroup: 1000
